{% set name = "policyuniverse" %}
{% set version = "1.5.1.20230817" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/policyuniverse-{{ version }}.tar.gz
  sha256: 7920896195af163230635f1a5cee0958f56003ef8c421f805ec81f134f80a57c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - policyuniverse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Netflix-Skunkworks/policyuniverse
  summary: Parse and Process AWS IAM Policies, Statements, ARNs, and wildcards.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
